// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbhatwmfoanxkwdozlzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiaGF0d21mb2FueGt3ZG96bHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDk3NDAsImV4cCI6MjA3MTA4NTc0MH0.pqUd5UsruGBPOxiSOZcza56EqUV7ym92iWlb7ir-Sww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});